tap argoproj/tap
tap derailed/k9s
tap homebrew/core
tap homebrew/bundle
tap homebrew/cask-fonts
tap homebrew/services
tap homebrew/cask
tap cloudflare/cloudflare
tap microsoft/git
tap minio/stable
tap rcmdnk/file
brew ca-certificates
brew awscli
brew curl
brew git
brew helm
brew htop
brew iproute2mac
brew ipmitool
brew jq
brew kubectx
brew kubernetes-cli
brew mkcert
brew mtr
brew nmap
brew pyenv
brew python@3.8
brew speedtest-cli
brew tig
brew tmux
brew tree
brew vault
brew vault-cli
brew velero
brew watch
brew wget
brew yq
brew zsh-completions
brew argoproj/tap/argo
brew derailed/k9s/k9s
cask chromium
cask iterm2
cask git-credential-manager-core
cask google-chrome
cask rectangle
cask visual-studio-code
cask wireshark
cask zoom
appstore 937984704   Amphetamine
appstore 1295203466  Microsoft Remote Desktop
appstore 425424353   The Unarchiver